version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: cajas_ventas
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: cajas_ventas_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql_cajas.sql:/docker-entrypoint-initdb.d/mysql_cajas.sql

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: bodega_inventario
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: SqlServer1234!
      MSSQL_DB: bodega_inventario_db
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  postgres:
    image: postgres:15
    container_name: corporativo_finanzas
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres1234
      POSTGRES_DB: corporativo_finanzas_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres_finanzas.sql:/docker-entrypoint-initdb.d/postgres_finanzas.sql

volumes:
  mysql_data:
  sqlserver_data:
  postgres_data:
